### ISSUE TITLE
[RP IVR] Sync IVR prompt mapping with Admindashboard

### ISSUE THREAD

**Issue by vivek-kumar-pandey** [DostEducation/RP_IVR_callback#42]
**Describe the bug**
Currently when we fetch the data for some columns like `has_smartphone`  column from ivr prompt, we get a string data but need to store it in boolean

**Expected behavior**
- [x] The value should be stored in boolean(true/false)
- [x] Fix the issue related to values getting separated by hyphen as well. It should only be separated by underscore.
- [x] Backfill the data that in not matching

**Screenshots**
NA

**Additional context**
NA

**Acceptance Criteria**
The data is stored correctly in the database. 

**Documentation**
Add whatever documentation will be required here.

**Comment by GauravGusain98** [comment]
This is completed. Closing this now.
