### ISSUE TITLE
Data Leak b/w Kookoo Reports and Database

### ISSUE THREAD

**Issue by gandhisonia** [DostEducation/RP_IVR_callback#7]
**Describe the bug**
We could observe some SIDs in Kookoo Reports which were not a part of the database.

**To Reproduce**
1. https://drive.google.com/file/d/1CJzylXxbcGRFsS2jsIZIuHhknWnQalKK/view?usp=sharing
2. SIDs: 918907583390427411, 918908661790731661, 918905484290815531
3. Compare other days' data for inbound/outbound with Kookoo reports

**Expected behavior**
Number of records of SIDs should match in both.

**Screenshots**
NA

**Environment (please complete the following information):**
NA

**Additional context**
Next Steps -- Observe differences for more days, and share the observations with Kookoo to figure out the cause and solution

**Comment by rudresh** [comment]
Sharing my observation here. We can take this to Kookoo team and ask the reason for not getting the callback.

##**Inbound calls**
1. The SID doesn’t match with the SID received in the callback. 
2. What does duration signifies with the inbound call report?
3. **On 3-May**
    1. No. of records in the report - **108**
    2. No. of records via Kookoo callback - **85**
    3. No. of records missing in Database - **23**
4. On **30-Apr**
    1. No. of records in the report - **185**
    2. No. of records via Kookoo callback- **156**
    3. No. of records missing in Database - **29**


##**Outbound Calls**
1. Duration column has values for non answered calls as well. What information does the duration column contain, is it the ringing time? 
2. The missing SID are not available in the kookoo logs as well. 
2. **On 3-May**
    1. No. of SID in Report has - **1610** 
    2. No. of SID  via Kookoo callback - **1548**
    3. No. of SID leaked - **62**
3. On **30-Apr**
    1. No. of SID in Report - **509** 
    2. No. of SID  via Kookoo callback - **469**
    3. No. of SID leaked - **40**

The missing SIDs for the outbound calls can be found [here](https://docs.google.com/spreadsheets/d/1ZSLUbQ3NMti-6LR19h-apIMTt5aw1dSz4A2UvWy3EMs/edit#gid=0).

**Comment by Satendra-SR** [comment]
This is accepted, closing now.
